version: '3.8'
services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:2.10.4'
    ports:
      - '80:80'
      - '443:443'
      - '8090:81'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./nginx.conf:/data/nginx/custom/http_top.conf
      - ./letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - frontend-network
      - backend-network
      - db-network

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    env_file:
      - frontend/.env
    networks:
      - frontend-network
      - backend-network

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: postgres://app:changethis123@db:5432/app
    depends_on:
      - db
    networks:
      - backend-network
      - db-network

  db:
    image: postgres:13
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - db-network

networks:
  frontend-network:
  backend-network:
  db-network:
volumes:
  postgres_data:
     driver: local
